quarkus.banner.path=banner.txt

app.name=${project.name:Taix quarkus-backup}
app.version=${project.version:develop}

# Datasource configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=pass
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/qbs}
#quarkus.hibernate-orm.database.generation=update

# MQTT configuration
mqtt.host=${MQTT_HOST:localhost}
mqtt.port=${MQTT_PORT:1883}
mqtt.username=${MQTT_USERNAME:}
mqtt.password=${MQTT_PASSWORD:}