app.name=""
app.version=""

mp.messaging.outgoing.backup_status.connector=smallrye-mqtt
mp.messaging.outgoing.backup_status.host=localhost
mp.messaging.outgoing.backup_status.port=1883

#mp.messaging.outgoing.backup_status.username=username
#mp.messaging.outgoing.backup_status.password=password